const DB="mishap-v2", STORE="incidents", LS="mishap-incidents-v1";
let db, allItems=[], showingAll=false;
const $=id=>document.getElementById(id);
const uid=()=>{try{return crypto.randomUUID()}catch{return Date.now()+"-"+Math.random()}};
const localNow=()=>{let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
function readLS(){try{return JSON.parse(localStorage.getItem(LS)||"[]")}catch{return []}}
function writeLS(items){try{localStorage.setItem(LS,JSON.stringify(items))}catch{}}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=e=>e.target.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function idbAll(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function idbPut(x){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).put(x);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
function idbDelete(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
async function getAll(){let items=[];try{items=await idbAll()}catch{}const backup=readLS();if(items.length===0&&backup.length){for(const x of backup){try{await idbPut(x)}catch{}}items=backup}if(items.length){writeLS(items)}return items.sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
async function saveItem(x){await idbPut(x);const current=readLS().filter(i=>i.id!==x.id);current.push(x);writeLS(current)}
async function removeItem(id){try{await idbDelete(id)}catch{}writeLS(readLS().filter(i=>i.id!==id))}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function last7(items){return items.filter(i=>Date.now()-new Date(i.date).getTime()<=604800000)}
function top(items,key){const m={};items.forEach(x=>{const v=x[key]||"Other";m[v]=(m[v]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]||["—",0]}
function renderStats(items){const w=last7(items),t=top(w,"trigger"),ty=top(w,"type");$("stats").innerHTML=`<div class="stat"><div class="stat-icon">▣</div><div class="stat-label">This week</div><div class="stat-value">${w.length}</div><div class="stat-sub">mishaps</div></div><div class="stat"><div class="stat-icon">!</div><div class="stat-label">Major</div><div class="stat-value">${w.filter(x=>x.severity==="Major").length}</div><div class="stat-sub">this week</div></div><div class="stat"><div class="stat-icon">♨</div><div class="stat-label">Top trigger</div><div class="stat-value">${esc(t[0])}</div><div class="stat-sub">${t[1]} time${t[1]===1?"":"s"}</div></div><div class="stat"><div class="stat-icon">↗</div><div class="stat-label">Top type</div><div class="stat-value">${esc(ty[0])}</div><div class="stat-sub">${ty[1]} incident${ty[1]===1?"":"s"}</div></div>`}
function incidentHTML(x){const d=new Date(x.date),month=d.toLocaleString(undefined,{month:"short"}).toUpperCase();return `<article class="incident"><div class="inc-date"><strong>${d.getDate()}</strong><span>${month}</span></div><div class="inc-main"><div class="food">${esc(x.food)}</div><div class="meta"><span class="tag">${esc(x.trigger)}</span><span class="sev ${esc(x.severity)}">● ${esc(x.severity)}</span>${x.context?`<span class="context">${esc(x.context)}</span>`:""}</div></div><button class="delete" data-id="${x.id}" aria-label="Delete">×</button><span class="arrow">›</span></article>`}
function renderList(items,limit=true){const list=limit?items.slice(0,8):items;$("incidentList").innerHTML=list.map(incidentHTML).join("");$("empty").classList.toggle("hidden",items.length>0);document.querySelectorAll(".delete").forEach(b=>b.onclick=async()=>{if(confirm("Delete this mishap?")){await removeItem(b.dataset.id);await render();if($('historyPanel')&&!$('historyPanel').classList.contains('hidden'))renderHistory()}});$("viewAll").textContent=items.length>8?(limit?"View all":"Show latest 8"):"";$("viewAll").classList.toggle("hidden",items.length<=8)}
async function render(){allItems=await getAll();renderStats(allItems);renderList(allItems,!showingAll)}
function setTab(tab){document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.add("hidden"));$(tab+"Panel")?.classList.remove("hidden");$("fab").classList.toggle("hidden",tab!=="home");window.scrollTo({top:0,behavior:"smooth"});if(tab==="history")renderHistory();if(tab==="insights")renderInsights();if(tab==="backup")renderBackup();if(tab==="settings")renderSettings()}
function renderHistory(){const box=$("historyList");if(!box)return;box.innerHTML=allItems.length?allItems.map(incidentHTML).join(""):`<div class="empty"><div>◎</div><strong>No mishaps yet</strong><p>Your history will appear here.</p></div>`;box.querySelectorAll(".delete").forEach(b=>b.onclick=async()=>{if(confirm("Delete this mishap?")){await removeItem(b.dataset.id);allItems=await getAll();render();renderHistory()}})}
function renderInsights(){const w=last7(allItems),t=top(w,"trigger"),ty=top(w,"type"),ctx=top(w,"context"),hungry=w.filter(x=>x.hunger?.startsWith("5")).length;$("insightsContent").innerHTML=w.length?`<div class="retro-grid"><div class="retro-box"><small>INCIDENTS · 7 DAYS</small><strong>${w.length}</strong></div><div class="retro-box"><small>MAJOR</small><strong>${w.filter(x=>x.severity==="Major").length}</strong></div><div class="retro-box"><small>TOP TRIGGER</small><strong>${esc(t[0])}</strong></div><div class="retro-box"><small>TOP TYPE</small><strong>${esc(ty[0])}</strong></div></div><div class="insight"><strong>Pattern</strong><p>${esc(t[0])} is the most common trigger. ${ctx[0]!=="—"?`Most incidents happened in ${esc(ctx[0])}.`:"Add context to incidents to discover where patterns happen."}</p></div><div class="insight"><strong>Hunger signal</strong><p>${hungry?`${hungry} incident${hungry===1?" was":"s were"} logged at extreme hunger.`:"No extreme-hunger incidents recorded this week."}</p></div><div class="insight"><strong>Next experiment</strong><p>${t[0]==="Social event"?"Decide your food and drink limit before the event.":t[0]==="Hunger"?"Have a planned protein-rich snack before your vulnerable meal.":"Keep logging for another week so recurring triggers become clearer."}</p></div>`:`<div class="empty"><div>▥</div><strong>Not enough data yet</strong><p>Log a few mishaps and your weekly patterns will appear here.</p></div>`}
function renderBackup(){const c=$("backupContent");c.innerHTML=`<div class="backup-card"><h3>Your data stays on this device</h3><p>Export a JSON backup if you want a copy. Import it later to restore your mishaps.</p><div class="backup-actions"><button class="secondary" id="exportBtn">Export backup</button><label class="secondary file-btn">Import backup<input id="importFile" type="file" accept="application/json"></label></div></div>`;$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(allItems,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`mishap-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};$("importFile").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported))throw Error();for(const x of imported)if(x.id&&x.date&&x.food)await saveItem(x);await render();alert(`Imported ${imported.length} mishap${imported.length===1?"":"s"}.`)}catch{alert("That backup file is not valid.")}}}
function renderSettings(){$("settingsContent").innerHTML=`<div class="backup-card"><h3>Storage</h3><p>${allItems.length} mishap${allItems.length===1?"":"s"} stored locally on this device.</p><button class="danger-btn" id="clearAll">Delete all mishaps</button></div><div class="backup-card"><h3>About Mishap</h3><p>Local-first retrospective tracker. No account. No backend. No analytics.</p></div>`;$("clearAll").onclick=async()=>{if(!allItems.length)return;if(confirm("Delete ALL mishaps from this device? This cannot be undone.")){for(const x of allItems)await removeItem(x.id);allItems=[];await render();renderSettings()}}}
$("toggleForm").onclick=()=>{const f=$("mishapForm");f.classList.toggle("hidden");$("formChevron").textContent=f.classList.contains("hidden")?"⌄":"⌃"};$("fab").onclick=()=>{setTab("home");if($("mishapForm").classList.contains("hidden"))$("toggleForm").click();setTimeout(()=>$('food').focus(),150)};$("date").value=localNow();
$("mishapForm").onsubmit=async e=>{e.preventDefault();const x={id:uid(),date:$("date").value,food:$("food").value.trim(),quantity:$("quantity").value.trim(),severity:$("severity").value,type:$("type").value,trigger:$("trigger").value,hunger:$("hunger").value,context:$("context").value.trim(),why:$("why").value.trim(),impact:$("impact").value.trim(),next:$("next").value.trim()};try{await saveItem(x)}catch{alert("Could not save this entry on the device.");return}e.target.reset();$("date").value=localNow();$("mishapForm").classList.add("hidden");$("formChevron").textContent="⌄";await render();alert("Mishap saved ✓")};
$("viewAll").onclick=()=>{showingAll=!showingAll;renderList(allItems,!showingAll)};
$("moreBtn").onclick=()=>setTab("settings");$("closeRetro").onclick=()=>$("retro").classList.add("hidden");
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
openDB().then(render).catch(async()=>{allItems=readLS();renderStats(allItems);renderList(allItems);});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));